FROM node:20

# Set working directory
WORKDIR /app

# Copy only package files first (meilleur cache Docker)
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY backend .

# Expose backend port
EXPOSE 5000

# Start app
CMD ["node", "index.js"]
